---
title: "2. More on R & Building Packages"
author: "J. Hathaway"
format: revealjs
---

## Today's agenda

- Going through the process of
  - building and R package
  - publishing our R package to GitHub and GitHub Pages
  - Installing our R package locally
  - Installing R packages from GitHub
- Overview of this week's and next week's plan and assignments

## This week's plan

- Tuesday: Introduction to R packages and VSCode Setup (Today)
- Thursday: More on R packages (Thursday)

## Introduction to our course r package

- [DS 250 Gun Deaths Assignment](https://byuistats.github.io/M335/weekly_projects/cs04_details.html)
- [US Deaths](https://www.cdc.gov/nchs/data_access/VitalStatsOnline.htm#Mortality_Multiple)
- [Private Github File Hathaway Built](https://github.com/KSUDS/p2_hathaway/blob/main/_functions.R)

## Redo on our Repos

- Let's delete the death repos we created last class from Github
- Let's fork [simplemaths](https://github.com/byuirpytooling/simplemaths) to our personal GitHub accounts.
  1. Clone our forked repos to our local machines
  2. Add your assigned function
  3. Test locally
  4. Do a pull request to the original repo
  5. Install the package from GitHub and use your function

## Let's discuss our [usdeaths package](https://github.com/byuirpytooling/usdeaths)

- What functions should we include?
- What assignments can each of us take?

## Pitches on your personal package ideas

- What kind of package would you like to build for your personal use?

## Class Assignments

 1. Make sure your environment is setup and that you can publish to GitHub pages
 2. Read through The [Getting started section (Chapters 1-5)](https://r-pkgs.org/)
 3. Create your own package repository for your personal R package.
